# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ftdx1200_eq_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_YaesuFTdx1200_3000_EQ_Utility(object):
    def setupUi(self, YaesuFTdx1200_3000_EQ_Utility):
        YaesuFTdx1200_3000_EQ_Utility.setObjectName("YaesuFTdx1200_3000_EQ_Utility")
        YaesuFTdx1200_3000_EQ_Utility.resize(995, 659)
        YaesuFTdx1200_3000_EQ_Utility.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}\n"
"\n"
"QLCDNumber{color:rgb(0, 0, 0)}")
        self.centralwidget = QtWidgets.QWidget(YaesuFTdx1200_3000_EQ_Utility)
        self.centralwidget.setObjectName("centralwidget")
        self.ProcOffFrame = QtWidgets.QGroupBox(self.centralwidget)
        self.ProcOffFrame.setGeometry(QtCore.QRect(10, 10, 971, 211))
        self.ProcOffFrame.setObjectName("ProcOffFrame")
        self.ProcOffEQ1Frame = QtWidgets.QGroupBox(self.ProcOffFrame)
        self.ProcOffEQ1Frame.setGeometry(QtCore.QRect(10, 30, 311, 161))
        self.ProcOffEQ1Frame.setStyleSheet("")
        self.ProcOffEQ1Frame.setObjectName("ProcOffEQ1Frame")
        self.offeq1FreqLabel = QtWidgets.QLabel(self.ProcOffEQ1Frame)
        self.offeq1FreqLabel.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.offeq1FreqLabel.setObjectName("offeq1FreqLabel")
        self.poffeq1Freq = QtWidgets.QSlider(self.ProcOffEQ1Frame)
        self.poffeq1Freq.setGeometry(QtCore.QRect(90, 60, 161, 22))
        self.poffeq1Freq.setMinimum(1)
        self.poffeq1Freq.setMaximum(7)
        self.poffeq1Freq.setPageStep(1)
        self.poffeq1Freq.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq1Freq.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poffeq1Freq.setTickInterval(1)
        self.poffeq1Freq.setObjectName("poffeq1Freq")
        self.poffeq1FreqLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame)
        self.poffeq1FreqLcd.setGeometry(QtCore.QRect(260, 60, 41, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.poffeq1FreqLcd.setFont(font)
        self.poffeq1FreqLcd.setAutoFillBackground(True)
        self.poffeq1FreqLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}")
        self.poffeq1FreqLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq1FreqLcd.setDigitCount(4)
        self.poffeq1FreqLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq1FreqLcd.setObjectName("poffeq1FreqLcd")
        self.offeq1LvlLabel = QtWidgets.QLabel(self.ProcOffEQ1Frame)
        self.offeq1LvlLabel.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.offeq1LvlLabel.setObjectName("offeq1LvlLabel")
        self.poffeq1Level = QtWidgets.QSlider(self.ProcOffEQ1Frame)
        self.poffeq1Level.setGeometry(QtCore.QRect(90, 90, 161, 22))
        self.poffeq1Level.setMinimum(-20)
        self.poffeq1Level.setMaximum(10)
        self.poffeq1Level.setPageStep(1)
        self.poffeq1Level.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq1Level.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poffeq1Level.setTickInterval(1)
        self.poffeq1Level.setObjectName("poffeq1Level")
        self.poffeq1LevelLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame)
        self.poffeq1LevelLcd.setGeometry(QtCore.QRect(260, 90, 41, 23))
        self.poffeq1LevelLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq1LevelLcd.setDigitCount(4)
        self.poffeq1LevelLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq1LevelLcd.setObjectName("poffeq1LevelLcd")
        self.offeq1BWLabel = QtWidgets.QLabel(self.ProcOffEQ1Frame)
        self.offeq1BWLabel.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.offeq1BWLabel.setObjectName("offeq1BWLabel")
        self.poffeq1Bw = QtWidgets.QSlider(self.ProcOffEQ1Frame)
        self.poffeq1Bw.setGeometry(QtCore.QRect(90, 120, 161, 22))
        self.poffeq1Bw.setMinimum(1)
        self.poffeq1Bw.setMaximum(10)
        self.poffeq1Bw.setPageStep(1)
        self.poffeq1Bw.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq1Bw.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poffeq1Bw.setTickInterval(1)
        self.poffeq1Bw.setObjectName("poffeq1Bw")
        self.poffeq1BwLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame)
        self.poffeq1BwLcd.setGeometry(QtCore.QRect(260, 120, 41, 23))
        self.poffeq1BwLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq1BwLcd.setDigitCount(4)
        self.poffeq1BwLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq1BwLcd.setObjectName("poffeq1BwLcd")
        self.poffeq1Control = QtWidgets.QComboBox(self.ProcOffEQ1Frame)
        self.poffeq1Control.setGeometry(QtCore.QRect(200, 20, 104, 26))
        self.poffeq1Control.setObjectName("poffeq1Control")
        self.poffeq1Control.addItem("")
        self.poffeq1Control.addItem("")
        self.label = QtWidgets.QLabel(self.ProcOffEQ1Frame)
        self.label.setGeometry(QtCore.QRect(140, 20, 60, 21))
        self.label.setObjectName("label")
        self.ProcOffEQ1Frame_2 = QtWidgets.QGroupBox(self.ProcOffFrame)
        self.ProcOffEQ1Frame_2.setGeometry(QtCore.QRect(330, 30, 311, 161))
        self.ProcOffEQ1Frame_2.setStyleSheet("")
        self.ProcOffEQ1Frame_2.setObjectName("ProcOffEQ1Frame_2")
        self.offeq1FreqLabel_2 = QtWidgets.QLabel(self.ProcOffEQ1Frame_2)
        self.offeq1FreqLabel_2.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.offeq1FreqLabel_2.setObjectName("offeq1FreqLabel_2")
        self.poffeq2Freq = QtWidgets.QSlider(self.ProcOffEQ1Frame_2)
        self.poffeq2Freq.setGeometry(QtCore.QRect(90, 60, 161, 22))
        self.poffeq2Freq.setMinimum(7)
        self.poffeq2Freq.setMaximum(15)
        self.poffeq2Freq.setPageStep(1)
        self.poffeq2Freq.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq2Freq.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poffeq2Freq.setTickInterval(1)
        self.poffeq2Freq.setObjectName("poffeq2Freq")
        self.poffeq2FreqLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_2)
        self.poffeq2FreqLcd.setGeometry(QtCore.QRect(260, 60, 41, 23))
        self.poffeq2FreqLcd.setAutoFillBackground(True)
        self.poffeq2FreqLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}")
        self.poffeq2FreqLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq2FreqLcd.setDigitCount(4)
        self.poffeq2FreqLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq2FreqLcd.setObjectName("poffeq2FreqLcd")
        self.offeq1LvlLabel_2 = QtWidgets.QLabel(self.ProcOffEQ1Frame_2)
        self.offeq1LvlLabel_2.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.offeq1LvlLabel_2.setObjectName("offeq1LvlLabel_2")
        self.poffeq2Level = QtWidgets.QSlider(self.ProcOffEQ1Frame_2)
        self.poffeq2Level.setGeometry(QtCore.QRect(90, 90, 161, 22))
        self.poffeq2Level.setMinimum(-20)
        self.poffeq2Level.setMaximum(10)
        self.poffeq2Level.setPageStep(1)
        self.poffeq2Level.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq2Level.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poffeq2Level.setTickInterval(1)
        self.poffeq2Level.setObjectName("poffeq2Level")
        self.poffeq2LevelLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_2)
        self.poffeq2LevelLcd.setGeometry(QtCore.QRect(260, 90, 41, 23))
        self.poffeq2LevelLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq2LevelLcd.setDigitCount(4)
        self.poffeq2LevelLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq2LevelLcd.setObjectName("poffeq2LevelLcd")
        self.offeq1BWLabel_2 = QtWidgets.QLabel(self.ProcOffEQ1Frame_2)
        self.offeq1BWLabel_2.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.offeq1BWLabel_2.setObjectName("offeq1BWLabel_2")
        self.poffeq2Bw = QtWidgets.QSlider(self.ProcOffEQ1Frame_2)
        self.poffeq2Bw.setGeometry(QtCore.QRect(90, 120, 161, 22))
        self.poffeq2Bw.setMinimum(1)
        self.poffeq2Bw.setMaximum(10)
        self.poffeq2Bw.setPageStep(1)
        self.poffeq2Bw.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq2Bw.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poffeq2Bw.setTickInterval(1)
        self.poffeq2Bw.setObjectName("poffeq2Bw")
        self.poffeq2BwLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_2)
        self.poffeq2BwLcd.setGeometry(QtCore.QRect(260, 120, 41, 23))
        self.poffeq2BwLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq2BwLcd.setDigitCount(4)
        self.poffeq2BwLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq2BwLcd.setObjectName("poffeq2BwLcd")
        self.poffeq2Control = QtWidgets.QComboBox(self.ProcOffEQ1Frame_2)
        self.poffeq2Control.setGeometry(QtCore.QRect(200, 20, 104, 26))
        self.poffeq2Control.setObjectName("poffeq2Control")
        self.poffeq2Control.addItem("")
        self.poffeq2Control.addItem("")
        self.label_2 = QtWidgets.QLabel(self.ProcOffEQ1Frame_2)
        self.label_2.setGeometry(QtCore.QRect(140, 20, 60, 21))
        self.label_2.setObjectName("label_2")
        self.ProcOffEQ1Frame_3 = QtWidgets.QGroupBox(self.ProcOffFrame)
        self.ProcOffEQ1Frame_3.setGeometry(QtCore.QRect(650, 30, 311, 161))
        self.ProcOffEQ1Frame_3.setStyleSheet("")
        self.ProcOffEQ1Frame_3.setObjectName("ProcOffEQ1Frame_3")
        self.offeq1FreqLabel_3 = QtWidgets.QLabel(self.ProcOffEQ1Frame_3)
        self.offeq1FreqLabel_3.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.offeq1FreqLabel_3.setObjectName("offeq1FreqLabel_3")
        self.poffeq3Freq = QtWidgets.QSlider(self.ProcOffEQ1Frame_3)
        self.poffeq3Freq.setGeometry(QtCore.QRect(90, 60, 161, 22))
        self.poffeq3Freq.setMinimum(15)
        self.poffeq3Freq.setMaximum(32)
        self.poffeq3Freq.setPageStep(1)
        self.poffeq3Freq.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq3Freq.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poffeq3Freq.setTickInterval(1)
        self.poffeq3Freq.setObjectName("poffeq3Freq")
        self.poffeq3FreqLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_3)
        self.poffeq3FreqLcd.setGeometry(QtCore.QRect(260, 60, 41, 23))
        self.poffeq3FreqLcd.setAutoFillBackground(True)
        self.poffeq3FreqLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}")
        self.poffeq3FreqLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq3FreqLcd.setDigitCount(4)
        self.poffeq3FreqLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq3FreqLcd.setObjectName("poffeq3FreqLcd")
        self.offeq1LvlLabel_3 = QtWidgets.QLabel(self.ProcOffEQ1Frame_3)
        self.offeq1LvlLabel_3.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.offeq1LvlLabel_3.setObjectName("offeq1LvlLabel_3")
        self.poffeq3Level = QtWidgets.QSlider(self.ProcOffEQ1Frame_3)
        self.poffeq3Level.setGeometry(QtCore.QRect(90, 90, 161, 22))
        self.poffeq3Level.setMinimum(-20)
        self.poffeq3Level.setMaximum(10)
        self.poffeq3Level.setPageStep(1)
        self.poffeq3Level.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq3Level.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poffeq3Level.setTickInterval(1)
        self.poffeq3Level.setObjectName("poffeq3Level")
        self.poffeq3LevelLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_3)
        self.poffeq3LevelLcd.setGeometry(QtCore.QRect(260, 90, 41, 23))
        self.poffeq3LevelLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq3LevelLcd.setDigitCount(4)
        self.poffeq3LevelLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq3LevelLcd.setObjectName("poffeq3LevelLcd")
        self.offeq1BWLabel_3 = QtWidgets.QLabel(self.ProcOffEQ1Frame_3)
        self.offeq1BWLabel_3.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.offeq1BWLabel_3.setObjectName("offeq1BWLabel_3")
        self.poffeq3Bw = QtWidgets.QSlider(self.ProcOffEQ1Frame_3)
        self.poffeq3Bw.setGeometry(QtCore.QRect(90, 120, 161, 22))
        self.poffeq3Bw.setMinimum(1)
        self.poffeq3Bw.setMaximum(10)
        self.poffeq3Bw.setPageStep(1)
        self.poffeq3Bw.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq3Bw.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poffeq3Bw.setTickInterval(1)
        self.poffeq3Bw.setObjectName("poffeq3Bw")
        self.poffeq3BwLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_3)
        self.poffeq3BwLcd.setGeometry(QtCore.QRect(260, 120, 41, 23))
        self.poffeq3BwLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq3BwLcd.setDigitCount(4)
        self.poffeq3BwLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq3BwLcd.setObjectName("poffeq3BwLcd")
        self.poffeq3Control = QtWidgets.QComboBox(self.ProcOffEQ1Frame_3)
        self.poffeq3Control.setGeometry(QtCore.QRect(200, 20, 104, 26))
        self.poffeq3Control.setObjectName("poffeq3Control")
        self.poffeq3Control.addItem("")
        self.poffeq3Control.addItem("")
        self.label_3 = QtWidgets.QLabel(self.ProcOffEQ1Frame_3)
        self.label_3.setGeometry(QtCore.QRect(140, 20, 60, 21))
        self.label_3.setObjectName("label_3")
        self.ProcOffFrame_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.ProcOffFrame_2.setGeometry(QtCore.QRect(10, 230, 971, 211))
        self.ProcOffFrame_2.setObjectName("ProcOffFrame_2")
        self.ProcOffEQ1Frame_4 = QtWidgets.QGroupBox(self.ProcOffFrame_2)
        self.ProcOffEQ1Frame_4.setGeometry(QtCore.QRect(10, 30, 311, 161))
        self.ProcOffEQ1Frame_4.setStyleSheet("")
        self.ProcOffEQ1Frame_4.setObjectName("ProcOffEQ1Frame_4")
        self.offeq1FreqLabel_4 = QtWidgets.QLabel(self.ProcOffEQ1Frame_4)
        self.offeq1FreqLabel_4.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.offeq1FreqLabel_4.setObjectName("offeq1FreqLabel_4")
        self.poneq1Freq = QtWidgets.QSlider(self.ProcOffEQ1Frame_4)
        self.poneq1Freq.setGeometry(QtCore.QRect(90, 60, 161, 22))
        self.poneq1Freq.setMinimum(1)
        self.poneq1Freq.setMaximum(7)
        self.poneq1Freq.setPageStep(1)
        self.poneq1Freq.setOrientation(QtCore.Qt.Horizontal)
        self.poneq1Freq.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poneq1Freq.setTickInterval(1)
        self.poneq1Freq.setObjectName("poneq1Freq")
        self.poneq1FreqLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_4)
        self.poneq1FreqLcd.setGeometry(QtCore.QRect(260, 60, 41, 23))
        self.poneq1FreqLcd.setAutoFillBackground(True)
        self.poneq1FreqLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}")
        self.poneq1FreqLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq1FreqLcd.setDigitCount(4)
        self.poneq1FreqLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq1FreqLcd.setObjectName("poneq1FreqLcd")
        self.offeq1LvlLabel_4 = QtWidgets.QLabel(self.ProcOffEQ1Frame_4)
        self.offeq1LvlLabel_4.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.offeq1LvlLabel_4.setObjectName("offeq1LvlLabel_4")
        self.poneq1Level = QtWidgets.QSlider(self.ProcOffEQ1Frame_4)
        self.poneq1Level.setGeometry(QtCore.QRect(90, 90, 161, 22))
        self.poneq1Level.setMinimum(-20)
        self.poneq1Level.setMaximum(10)
        self.poneq1Level.setPageStep(1)
        self.poneq1Level.setOrientation(QtCore.Qt.Horizontal)
        self.poneq1Level.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poneq1Level.setTickInterval(1)
        self.poneq1Level.setObjectName("poneq1Level")
        self.poneq1LevelLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_4)
        self.poneq1LevelLcd.setGeometry(QtCore.QRect(260, 90, 41, 23))
        self.poneq1LevelLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq1LevelLcd.setDigitCount(4)
        self.poneq1LevelLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq1LevelLcd.setObjectName("poneq1LevelLcd")
        self.offeq1BWLabel_4 = QtWidgets.QLabel(self.ProcOffEQ1Frame_4)
        self.offeq1BWLabel_4.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.offeq1BWLabel_4.setObjectName("offeq1BWLabel_4")
        self.poneq1Bw = QtWidgets.QSlider(self.ProcOffEQ1Frame_4)
        self.poneq1Bw.setGeometry(QtCore.QRect(90, 120, 161, 22))
        self.poneq1Bw.setMinimum(1)
        self.poneq1Bw.setMaximum(10)
        self.poneq1Bw.setPageStep(1)
        self.poneq1Bw.setOrientation(QtCore.Qt.Horizontal)
        self.poneq1Bw.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poneq1Bw.setTickInterval(1)
        self.poneq1Bw.setObjectName("poneq1Bw")
        self.poneq1BwLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_4)
        self.poneq1BwLcd.setGeometry(QtCore.QRect(260, 120, 41, 23))
        self.poneq1BwLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq1BwLcd.setDigitCount(4)
        self.poneq1BwLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq1BwLcd.setObjectName("poneq1BwLcd")
        self.poneq1Control = QtWidgets.QComboBox(self.ProcOffEQ1Frame_4)
        self.poneq1Control.setGeometry(QtCore.QRect(200, 20, 104, 26))
        self.poneq1Control.setObjectName("poneq1Control")
        self.poneq1Control.addItem("")
        self.poneq1Control.addItem("")
        self.label_4 = QtWidgets.QLabel(self.ProcOffEQ1Frame_4)
        self.label_4.setGeometry(QtCore.QRect(140, 20, 60, 21))
        self.label_4.setObjectName("label_4")
        self.ProcOffEQ1Frame_5 = QtWidgets.QGroupBox(self.ProcOffFrame_2)
        self.ProcOffEQ1Frame_5.setGeometry(QtCore.QRect(330, 30, 311, 161))
        self.ProcOffEQ1Frame_5.setStyleSheet("")
        self.ProcOffEQ1Frame_5.setObjectName("ProcOffEQ1Frame_5")
        self.offeq1FreqLabel_5 = QtWidgets.QLabel(self.ProcOffEQ1Frame_5)
        self.offeq1FreqLabel_5.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.offeq1FreqLabel_5.setObjectName("offeq1FreqLabel_5")
        self.poneq2Freq = QtWidgets.QSlider(self.ProcOffEQ1Frame_5)
        self.poneq2Freq.setGeometry(QtCore.QRect(90, 60, 161, 22))
        self.poneq2Freq.setMinimum(7)
        self.poneq2Freq.setMaximum(15)
        self.poneq2Freq.setPageStep(1)
        self.poneq2Freq.setOrientation(QtCore.Qt.Horizontal)
        self.poneq2Freq.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poneq2Freq.setTickInterval(1)
        self.poneq2Freq.setObjectName("poneq2Freq")
        self.poneq2FreqLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_5)
        self.poneq2FreqLcd.setGeometry(QtCore.QRect(260, 60, 41, 23))
        self.poneq2FreqLcd.setAutoFillBackground(True)
        self.poneq2FreqLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}")
        self.poneq2FreqLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq2FreqLcd.setDigitCount(4)
        self.poneq2FreqLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq2FreqLcd.setObjectName("poneq2FreqLcd")
        self.offeq1LvlLabel_5 = QtWidgets.QLabel(self.ProcOffEQ1Frame_5)
        self.offeq1LvlLabel_5.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.offeq1LvlLabel_5.setObjectName("offeq1LvlLabel_5")
        self.poneq2Level = QtWidgets.QSlider(self.ProcOffEQ1Frame_5)
        self.poneq2Level.setGeometry(QtCore.QRect(90, 90, 161, 22))
        self.poneq2Level.setMinimum(-20)
        self.poneq2Level.setMaximum(10)
        self.poneq2Level.setPageStep(1)
        self.poneq2Level.setOrientation(QtCore.Qt.Horizontal)
        self.poneq2Level.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poneq2Level.setTickInterval(1)
        self.poneq2Level.setObjectName("poneq2Level")
        self.poneq2LevelLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_5)
        self.poneq2LevelLcd.setGeometry(QtCore.QRect(260, 90, 41, 23))
        self.poneq2LevelLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq2LevelLcd.setDigitCount(4)
        self.poneq2LevelLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq2LevelLcd.setObjectName("poneq2LevelLcd")
        self.offeq1BWLabel_5 = QtWidgets.QLabel(self.ProcOffEQ1Frame_5)
        self.offeq1BWLabel_5.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.offeq1BWLabel_5.setObjectName("offeq1BWLabel_5")
        self.poneq2Bw = QtWidgets.QSlider(self.ProcOffEQ1Frame_5)
        self.poneq2Bw.setGeometry(QtCore.QRect(90, 120, 161, 22))
        self.poneq2Bw.setMinimum(1)
        self.poneq2Bw.setMaximum(10)
        self.poneq2Bw.setPageStep(1)
        self.poneq2Bw.setOrientation(QtCore.Qt.Horizontal)
        self.poneq2Bw.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poneq2Bw.setTickInterval(1)
        self.poneq2Bw.setObjectName("poneq2Bw")
        self.poneq2BwLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_5)
        self.poneq2BwLcd.setGeometry(QtCore.QRect(260, 120, 41, 23))
        self.poneq2BwLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq2BwLcd.setDigitCount(4)
        self.poneq2BwLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq2BwLcd.setObjectName("poneq2BwLcd")
        self.poneq2Control = QtWidgets.QComboBox(self.ProcOffEQ1Frame_5)
        self.poneq2Control.setGeometry(QtCore.QRect(200, 20, 104, 26))
        self.poneq2Control.setObjectName("poneq2Control")
        self.poneq2Control.addItem("")
        self.poneq2Control.addItem("")
        self.label_5 = QtWidgets.QLabel(self.ProcOffEQ1Frame_5)
        self.label_5.setGeometry(QtCore.QRect(140, 20, 60, 21))
        self.label_5.setObjectName("label_5")
        self.ProcOffEQ1Frame_6 = QtWidgets.QGroupBox(self.ProcOffFrame_2)
        self.ProcOffEQ1Frame_6.setGeometry(QtCore.QRect(650, 30, 311, 161))
        self.ProcOffEQ1Frame_6.setStyleSheet("")
        self.ProcOffEQ1Frame_6.setObjectName("ProcOffEQ1Frame_6")
        self.offeq1FreqLabel_6 = QtWidgets.QLabel(self.ProcOffEQ1Frame_6)
        self.offeq1FreqLabel_6.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.offeq1FreqLabel_6.setObjectName("offeq1FreqLabel_6")
        self.poneq3Freq = QtWidgets.QSlider(self.ProcOffEQ1Frame_6)
        self.poneq3Freq.setGeometry(QtCore.QRect(90, 60, 161, 22))
        self.poneq3Freq.setMinimum(15)
        self.poneq3Freq.setMaximum(32)
        self.poneq3Freq.setPageStep(1)
        self.poneq3Freq.setOrientation(QtCore.Qt.Horizontal)
        self.poneq3Freq.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poneq3Freq.setTickInterval(1)
        self.poneq3Freq.setObjectName("poneq3Freq")
        self.poneq3FreqLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_6)
        self.poneq3FreqLcd.setGeometry(QtCore.QRect(260, 60, 41, 23))
        self.poneq3FreqLcd.setAutoFillBackground(True)
        self.poneq3FreqLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}")
        self.poneq3FreqLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq3FreqLcd.setDigitCount(4)
        self.poneq3FreqLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq3FreqLcd.setObjectName("poneq3FreqLcd")
        self.offeq1LvlLabel_6 = QtWidgets.QLabel(self.ProcOffEQ1Frame_6)
        self.offeq1LvlLabel_6.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.offeq1LvlLabel_6.setObjectName("offeq1LvlLabel_6")
        self.poneq3Level = QtWidgets.QSlider(self.ProcOffEQ1Frame_6)
        self.poneq3Level.setGeometry(QtCore.QRect(90, 90, 161, 22))
        self.poneq3Level.setMinimum(-20)
        self.poneq3Level.setMaximum(10)
        self.poneq3Level.setPageStep(1)
        self.poneq3Level.setOrientation(QtCore.Qt.Horizontal)
        self.poneq3Level.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poneq3Level.setTickInterval(1)
        self.poneq3Level.setObjectName("poneq3Level")
        self.poneq3LevelLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_6)
        self.poneq3LevelLcd.setGeometry(QtCore.QRect(260, 90, 41, 23))
        self.poneq3LevelLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq3LevelLcd.setDigitCount(4)
        self.poneq3LevelLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq3LevelLcd.setObjectName("poneq3LevelLcd")
        self.offeq1BWLabel_6 = QtWidgets.QLabel(self.ProcOffEQ1Frame_6)
        self.offeq1BWLabel_6.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.offeq1BWLabel_6.setObjectName("offeq1BWLabel_6")
        self.poneq3Bw = QtWidgets.QSlider(self.ProcOffEQ1Frame_6)
        self.poneq3Bw.setGeometry(QtCore.QRect(90, 120, 161, 22))
        self.poneq3Bw.setMinimum(1)
        self.poneq3Bw.setMaximum(10)
        self.poneq3Bw.setPageStep(1)
        self.poneq3Bw.setOrientation(QtCore.Qt.Horizontal)
        self.poneq3Bw.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.poneq3Bw.setTickInterval(1)
        self.poneq3Bw.setObjectName("poneq3Bw")
        self.poneq3BwLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame_6)
        self.poneq3BwLcd.setGeometry(QtCore.QRect(260, 120, 41, 23))
        self.poneq3BwLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq3BwLcd.setDigitCount(4)
        self.poneq3BwLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq3BwLcd.setObjectName("poneq3BwLcd")
        self.poneq3Control = QtWidgets.QComboBox(self.ProcOffEQ1Frame_6)
        self.poneq3Control.setGeometry(QtCore.QRect(200, 20, 104, 26))
        self.poneq3Control.setObjectName("poneq3Control")
        self.poneq3Control.addItem("")
        self.poneq3Control.addItem("")
        self.label_6 = QtWidgets.QLabel(self.ProcOffEQ1Frame_6)
        self.label_6.setGeometry(QtCore.QRect(140, 20, 60, 21))
        self.label_6.setObjectName("label_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 450, 131, 61))
        self.groupBox.setObjectName("groupBox")
        self.voiceprocControl = QtWidgets.QComboBox(self.groupBox)
        self.voiceprocControl.setGeometry(QtCore.QRect(10, 20, 111, 26))
        self.voiceprocControl.setObjectName("voiceprocControl")
        self.voiceprocControl.addItem("")
        self.voiceprocControl.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 450, 131, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.micEqControl = QtWidgets.QComboBox(self.groupBox_2)
        self.micEqControl.setGeometry(QtCore.QRect(10, 20, 111, 26))
        self.micEqControl.setObjectName("micEqControl")
        self.micEqControl.addItem("")
        self.micEqControl.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(290, 450, 361, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comPortInput = QtWidgets.QComboBox(self.groupBox_3)
        self.comPortInput.setGeometry(QtCore.QRect(10, 50, 231, 26))
        self.comPortInput.setObjectName("comPortInput")
        self.comPortInput.addItem("")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 211, 20))
        self.label_7.setObjectName("label_7")
        self.baudRate = QtWidgets.QComboBox(self.groupBox_3)
        self.baudRate.setGeometry(QtCore.QRect(250, 50, 104, 26))
        self.baudRate.setObjectName("baudRate")
        self.baudRate.addItem("")
        self.baudRate.addItem("")
        self.baudRate.addItem("")
        self.baudRate.addItem("")
        self.baudRate.addItem("")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(259, 30, 81, 20))
        self.label_8.setObjectName("label_8")
        self.radioConnect = QtWidgets.QPushButton(self.groupBox_3)
        self.radioConnect.setGeometry(QtCore.QRect(50, 80, 113, 32))
        self.radioConnect.setObjectName("radioConnect")
        self.radioDisconnect = QtWidgets.QPushButton(self.groupBox_3)
        self.radioDisconnect.setGeometry(QtCore.QRect(190, 80, 113, 32))
        self.radioDisconnect.setObjectName("radioDisconnect")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(660, 450, 321, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.messageLabel = QtWidgets.QLabel(self.groupBox_4)
        self.messageLabel.setGeometry(QtCore.QRect(9, 15, 301, 101))
        self.messageLabel.setText("")
        self.messageLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.messageLabel.setWordWrap(True)
        self.messageLabel.setObjectName("messageLabel")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(9, 520, 271, 61))
        self.groupBox_5.setObjectName("groupBox_5")
        self.micGain = QtWidgets.QSlider(self.groupBox_5)
        self.micGain.setGeometry(QtCore.QRect(20, 30, 191, 22))
        self.micGain.setMinimum(0)
        self.micGain.setMaximum(100)
        self.micGain.setPageStep(1)
        self.micGain.setSliderPosition(0)
        self.micGain.setOrientation(QtCore.Qt.Horizontal)
        self.micGain.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.micGain.setTickInterval(10)
        self.micGain.setObjectName("micGain")
        self.micGainLcd = QtWidgets.QLCDNumber(self.groupBox_5)
        self.micGainLcd.setGeometry(QtCore.QRect(220, 30, 41, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.micGainLcd.setFont(font)
        self.micGainLcd.setAutoFillBackground(True)
        self.micGainLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}")
        self.micGainLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.micGainLcd.setDigitCount(4)
        self.micGainLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.micGainLcd.setObjectName("micGainLcd")
        YaesuFTdx1200_3000_EQ_Utility.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(YaesuFTdx1200_3000_EQ_Utility)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 995, 22))
        self.menubar.setObjectName("menubar")
        YaesuFTdx1200_3000_EQ_Utility.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(YaesuFTdx1200_3000_EQ_Utility)
        self.statusbar.setObjectName("statusbar")
        YaesuFTdx1200_3000_EQ_Utility.setStatusBar(self.statusbar)

        self.retranslateUi(YaesuFTdx1200_3000_EQ_Utility)
        QtCore.QMetaObject.connectSlotsByName(YaesuFTdx1200_3000_EQ_Utility)

    def retranslateUi(self, YaesuFTdx1200_3000_EQ_Utility):
        _translate = QtCore.QCoreApplication.translate
        YaesuFTdx1200_3000_EQ_Utility.setWindowTitle(_translate("YaesuFTdx1200_3000_EQ_Utility", "Yaesu FTdx1200 / 3000 EQ Utility"))
        self.ProcOffFrame.setTitle(_translate("YaesuFTdx1200_3000_EQ_Utility", "Voice Processor Off EQ Settings"))
        self.ProcOffEQ1Frame.setTitle(_translate("YaesuFTdx1200_3000_EQ_Utility", "EQ 1"))
        self.offeq1FreqLabel.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Frequency"))
        self.offeq1LvlLabel.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Level"))
        self.offeq1BWLabel.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Bandwidth"))
        self.poffeq1Control.setItemText(0, _translate("YaesuFTdx1200_3000_EQ_Utility", "Off"))
        self.poffeq1Control.setItemText(1, _translate("YaesuFTdx1200_3000_EQ_Utility", "On"))
        self.label.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "On/Off"))
        self.ProcOffEQ1Frame_2.setTitle(_translate("YaesuFTdx1200_3000_EQ_Utility", "EQ 2"))
        self.offeq1FreqLabel_2.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Frequency"))
        self.offeq1LvlLabel_2.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Level"))
        self.offeq1BWLabel_2.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Bandwidth"))
        self.poffeq2Control.setItemText(0, _translate("YaesuFTdx1200_3000_EQ_Utility", "Off"))
        self.poffeq2Control.setItemText(1, _translate("YaesuFTdx1200_3000_EQ_Utility", "On"))
        self.label_2.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "On/Off"))
        self.ProcOffEQ1Frame_3.setTitle(_translate("YaesuFTdx1200_3000_EQ_Utility", "EQ 3"))
        self.offeq1FreqLabel_3.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Frequency"))
        self.offeq1LvlLabel_3.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Level"))
        self.offeq1BWLabel_3.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Bandwidth"))
        self.poffeq3Control.setItemText(0, _translate("YaesuFTdx1200_3000_EQ_Utility", "Off"))
        self.poffeq3Control.setItemText(1, _translate("YaesuFTdx1200_3000_EQ_Utility", "On"))
        self.label_3.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "On/Off"))
        self.ProcOffFrame_2.setTitle(_translate("YaesuFTdx1200_3000_EQ_Utility", "Voice Processor On EQ Settings"))
        self.ProcOffEQ1Frame_4.setTitle(_translate("YaesuFTdx1200_3000_EQ_Utility", "EQ 1"))
        self.offeq1FreqLabel_4.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Frequency"))
        self.offeq1LvlLabel_4.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Level"))
        self.offeq1BWLabel_4.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Bandwidth"))
        self.poneq1Control.setItemText(0, _translate("YaesuFTdx1200_3000_EQ_Utility", "Off"))
        self.poneq1Control.setItemText(1, _translate("YaesuFTdx1200_3000_EQ_Utility", "On"))
        self.label_4.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "On/Off"))
        self.ProcOffEQ1Frame_5.setTitle(_translate("YaesuFTdx1200_3000_EQ_Utility", "EQ 2"))
        self.offeq1FreqLabel_5.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Frequency"))
        self.offeq1LvlLabel_5.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Level"))
        self.offeq1BWLabel_5.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Bandwidth"))
        self.poneq2Control.setItemText(0, _translate("YaesuFTdx1200_3000_EQ_Utility", "Off"))
        self.poneq2Control.setItemText(1, _translate("YaesuFTdx1200_3000_EQ_Utility", "On"))
        self.label_5.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "On/Off"))
        self.ProcOffEQ1Frame_6.setTitle(_translate("YaesuFTdx1200_3000_EQ_Utility", "EQ 3"))
        self.offeq1FreqLabel_6.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Frequency"))
        self.offeq1LvlLabel_6.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Level"))
        self.offeq1BWLabel_6.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Bandwidth"))
        self.poneq3Control.setItemText(0, _translate("YaesuFTdx1200_3000_EQ_Utility", "Off"))
        self.poneq3Control.setItemText(1, _translate("YaesuFTdx1200_3000_EQ_Utility", "On"))
        self.label_6.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "On/Off"))
        self.groupBox.setTitle(_translate("YaesuFTdx1200_3000_EQ_Utility", "Voice Processor"))
        self.voiceprocControl.setItemText(0, _translate("YaesuFTdx1200_3000_EQ_Utility", "Off"))
        self.voiceprocControl.setItemText(1, _translate("YaesuFTdx1200_3000_EQ_Utility", "On"))
        self.groupBox_2.setTitle(_translate("YaesuFTdx1200_3000_EQ_Utility", "Mic EQ"))
        self.micEqControl.setItemText(0, _translate("YaesuFTdx1200_3000_EQ_Utility", "Off"))
        self.micEqControl.setItemText(1, _translate("YaesuFTdx1200_3000_EQ_Utility", "On"))
        self.groupBox_3.setTitle(_translate("YaesuFTdx1200_3000_EQ_Utility", "Radio Connection"))
        self.comPortInput.setItemText(0, _translate("YaesuFTdx1200_3000_EQ_Utility", "Select Com Port"))
        self.label_7.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Com Port Selection"))
        self.baudRate.setItemText(0, _translate("YaesuFTdx1200_3000_EQ_Utility", "Set Baud"))
        self.baudRate.setItemText(1, _translate("YaesuFTdx1200_3000_EQ_Utility", "4800"))
        self.baudRate.setItemText(2, _translate("YaesuFTdx1200_3000_EQ_Utility", "9600"))
        self.baudRate.setItemText(3, _translate("YaesuFTdx1200_3000_EQ_Utility", "19200"))
        self.baudRate.setItemText(4, _translate("YaesuFTdx1200_3000_EQ_Utility", "38400"))
        self.label_8.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Baud Rate"))
        self.radioConnect.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Connect"))
        self.radioDisconnect.setText(_translate("YaesuFTdx1200_3000_EQ_Utility", "Disconnect"))
        self.groupBox_4.setTitle(_translate("YaesuFTdx1200_3000_EQ_Utility", "Status Messages"))
        self.groupBox_5.setTitle(_translate("YaesuFTdx1200_3000_EQ_Utility", "Mic Gain"))

