# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ftdx1200_eq_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(977, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ProcOffFrame = QtWidgets.QGroupBox(self.centralwidget)
        self.ProcOffFrame.setGeometry(QtCore.QRect(20, 10, 941, 211))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ProcOffFrame.setFont(font)
        self.ProcOffFrame.setAutoFillBackground(False)
        self.ProcOffFrame.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.ProcOffFrame.setFlat(False)
        self.ProcOffFrame.setObjectName("ProcOffFrame")
        self.ProcOffEQ1Frame = QtWidgets.QGroupBox(self.ProcOffFrame)
        self.ProcOffEQ1Frame.setGeometry(QtCore.QRect(10, 30, 301, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ProcOffEQ1Frame.setFont(font)
        self.ProcOffEQ1Frame.setAutoFillBackground(False)
        self.ProcOffEQ1Frame.setFlat(False)
        self.ProcOffEQ1Frame.setObjectName("ProcOffEQ1Frame")
        self.poffeq1Freq = QtWidgets.QSlider(self.ProcOffEQ1Frame)
        self.poffeq1Freq.setGeometry(QtCore.QRect(80, 50, 160, 22))
        self.poffeq1Freq.setMinimum(1)
        self.poffeq1Freq.setMaximum(7)
        self.poffeq1Freq.setSingleStep(1)
        self.poffeq1Freq.setPageStep(1)
        self.poffeq1Freq.setProperty("value", 1)
        self.poffeq1Freq.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq1Freq.setInvertedAppearance(False)
        self.poffeq1Freq.setInvertedControls(False)
        self.poffeq1Freq.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poffeq1Freq.setTickInterval(1)
        self.poffeq1Freq.setObjectName("poffeq1Freq")
        self.label = QtWidgets.QLabel(self.ProcOffEQ1Frame)
        self.label.setGeometry(QtCore.QRect(10, 50, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.poffeq1FreqLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame)
        self.poffeq1FreqLcd.setGeometry(QtCore.QRect(250, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poffeq1FreqLcd.setFont(font)
        self.poffeq1FreqLcd.setAutoFillBackground(True)
        self.poffeq1FreqLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poffeq1FreqLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poffeq1FreqLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq1FreqLcd.setLineWidth(1)
        self.poffeq1FreqLcd.setDigitCount(4)
        self.poffeq1FreqLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq1FreqLcd.setObjectName("poffeq1FreqLcd")
        self.label_2 = QtWidgets.QLabel(self.ProcOffEQ1Frame)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.poffeq1Level = QtWidgets.QSlider(self.ProcOffEQ1Frame)
        self.poffeq1Level.setGeometry(QtCore.QRect(80, 90, 160, 22))
        self.poffeq1Level.setMinimum(-20)
        self.poffeq1Level.setMaximum(10)
        self.poffeq1Level.setSingleStep(1)
        self.poffeq1Level.setPageStep(1)
        self.poffeq1Level.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq1Level.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poffeq1Level.setTickInterval(1)
        self.poffeq1Level.setObjectName("poffeq1Level")
        self.poffeq1LevelLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame)
        self.poffeq1LevelLcd.setGeometry(QtCore.QRect(250, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poffeq1LevelLcd.setFont(font)
        self.poffeq1LevelLcd.setAutoFillBackground(True)
        self.poffeq1LevelLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poffeq1LevelLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poffeq1LevelLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq1LevelLcd.setLineWidth(1)
        self.poffeq1LevelLcd.setDigitCount(4)
        self.poffeq1LevelLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq1LevelLcd.setObjectName("poffeq1LevelLcd")
        self.label_3 = QtWidgets.QLabel(self.ProcOffEQ1Frame)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.poffeq1Bw = QtWidgets.QSlider(self.ProcOffEQ1Frame)
        self.poffeq1Bw.setGeometry(QtCore.QRect(80, 130, 160, 22))
        self.poffeq1Bw.setMinimum(1)
        self.poffeq1Bw.setMaximum(10)
        self.poffeq1Bw.setSingleStep(1)
        self.poffeq1Bw.setPageStep(1)
        self.poffeq1Bw.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq1Bw.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poffeq1Bw.setTickInterval(1)
        self.poffeq1Bw.setObjectName("poffeq1Bw")
        self.poffeq1BwLcd = QtWidgets.QLCDNumber(self.ProcOffEQ1Frame)
        self.poffeq1BwLcd.setGeometry(QtCore.QRect(250, 130, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poffeq1BwLcd.setFont(font)
        self.poffeq1BwLcd.setAutoFillBackground(True)
        self.poffeq1BwLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poffeq1BwLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poffeq1BwLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq1BwLcd.setLineWidth(1)
        self.poffeq1BwLcd.setDigitCount(4)
        self.poffeq1BwLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq1BwLcd.setObjectName("poffeq1BwLcd")
        self.poffeq1Control = QtWidgets.QComboBox(self.ProcOffEQ1Frame)
        self.poffeq1Control.setGeometry(QtCore.QRect(180, 20, 104, 21))
        self.poffeq1Control.setObjectName("poffeq1Control")
        self.poffeq1Control.addItem("")
        self.poffeq1Control.addItem("")
        self.label_21 = QtWidgets.QLabel(self.ProcOffEQ1Frame)
        self.label_21.setGeometry(QtCore.QRect(140, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.ProcOffEQ2Frame = QtWidgets.QGroupBox(self.ProcOffFrame)
        self.ProcOffEQ2Frame.setGeometry(QtCore.QRect(320, 30, 301, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ProcOffEQ2Frame.setFont(font)
        self.ProcOffEQ2Frame.setAutoFillBackground(False)
        self.ProcOffEQ2Frame.setFlat(False)
        self.ProcOffEQ2Frame.setObjectName("ProcOffEQ2Frame")
        self.poffeq2Freq = QtWidgets.QSlider(self.ProcOffEQ2Frame)
        self.poffeq2Freq.setGeometry(QtCore.QRect(80, 50, 160, 22))
        self.poffeq2Freq.setMinimum(7)
        self.poffeq2Freq.setMaximum(15)
        self.poffeq2Freq.setSingleStep(1)
        self.poffeq2Freq.setPageStep(1)
        self.poffeq2Freq.setProperty("value", 7)
        self.poffeq2Freq.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq2Freq.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poffeq2Freq.setTickInterval(1)
        self.poffeq2Freq.setObjectName("poffeq2Freq")
        self.label_4 = QtWidgets.QLabel(self.ProcOffEQ2Frame)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.poffeq2FreqLcd = QtWidgets.QLCDNumber(self.ProcOffEQ2Frame)
        self.poffeq2FreqLcd.setGeometry(QtCore.QRect(250, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poffeq2FreqLcd.setFont(font)
        self.poffeq2FreqLcd.setAutoFillBackground(True)
        self.poffeq2FreqLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poffeq2FreqLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poffeq2FreqLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq2FreqLcd.setLineWidth(1)
        self.poffeq2FreqLcd.setDigitCount(4)
        self.poffeq2FreqLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq2FreqLcd.setObjectName("poffeq2FreqLcd")
        self.label_5 = QtWidgets.QLabel(self.ProcOffEQ2Frame)
        self.label_5.setGeometry(QtCore.QRect(40, 90, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.poffeq2Level = QtWidgets.QSlider(self.ProcOffEQ2Frame)
        self.poffeq2Level.setGeometry(QtCore.QRect(80, 90, 160, 22))
        self.poffeq2Level.setMinimum(-20)
        self.poffeq2Level.setMaximum(10)
        self.poffeq2Level.setSingleStep(1)
        self.poffeq2Level.setPageStep(1)
        self.poffeq2Level.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq2Level.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poffeq2Level.setTickInterval(1)
        self.poffeq2Level.setObjectName("poffeq2Level")
        self.poffeq2LevelLcd = QtWidgets.QLCDNumber(self.ProcOffEQ2Frame)
        self.poffeq2LevelLcd.setGeometry(QtCore.QRect(250, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poffeq2LevelLcd.setFont(font)
        self.poffeq2LevelLcd.setAutoFillBackground(True)
        self.poffeq2LevelLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poffeq2LevelLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poffeq2LevelLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq2LevelLcd.setLineWidth(1)
        self.poffeq2LevelLcd.setDigitCount(4)
        self.poffeq2LevelLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq2LevelLcd.setObjectName("poffeq2LevelLcd")
        self.label_6 = QtWidgets.QLabel(self.ProcOffEQ2Frame)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.poffeq2Bw = QtWidgets.QSlider(self.ProcOffEQ2Frame)
        self.poffeq2Bw.setGeometry(QtCore.QRect(80, 130, 160, 22))
        self.poffeq2Bw.setMinimum(1)
        self.poffeq2Bw.setMaximum(10)
        self.poffeq2Bw.setSingleStep(1)
        self.poffeq2Bw.setPageStep(1)
        self.poffeq2Bw.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq2Bw.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poffeq2Bw.setTickInterval(1)
        self.poffeq2Bw.setObjectName("poffeq2Bw")
        self.poffeq2BwLcd = QtWidgets.QLCDNumber(self.ProcOffEQ2Frame)
        self.poffeq2BwLcd.setGeometry(QtCore.QRect(250, 130, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poffeq2BwLcd.setFont(font)
        self.poffeq2BwLcd.setAutoFillBackground(True)
        self.poffeq2BwLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poffeq2BwLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poffeq2BwLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq2BwLcd.setLineWidth(1)
        self.poffeq2BwLcd.setDigitCount(4)
        self.poffeq2BwLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq2BwLcd.setObjectName("poffeq2BwLcd")
        self.poffeq2Control = QtWidgets.QComboBox(self.ProcOffEQ2Frame)
        self.poffeq2Control.setGeometry(QtCore.QRect(180, 20, 104, 21))
        self.poffeq2Control.setObjectName("poffeq2Control")
        self.poffeq2Control.addItem("")
        self.poffeq2Control.addItem("")
        self.label_22 = QtWidgets.QLabel(self.ProcOffEQ2Frame)
        self.label_22.setGeometry(QtCore.QRect(140, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.ProcOffEQ3Frame = QtWidgets.QGroupBox(self.ProcOffFrame)
        self.ProcOffEQ3Frame.setGeometry(QtCore.QRect(630, 30, 301, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ProcOffEQ3Frame.setFont(font)
        self.ProcOffEQ3Frame.setAutoFillBackground(False)
        self.ProcOffEQ3Frame.setFlat(False)
        self.ProcOffEQ3Frame.setObjectName("ProcOffEQ3Frame")
        self.poffeq3Freq = QtWidgets.QSlider(self.ProcOffEQ3Frame)
        self.poffeq3Freq.setGeometry(QtCore.QRect(80, 50, 160, 22))
        self.poffeq3Freq.setMinimum(15)
        self.poffeq3Freq.setMaximum(32)
        self.poffeq3Freq.setSingleStep(1)
        self.poffeq3Freq.setPageStep(1)
        self.poffeq3Freq.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq3Freq.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poffeq3Freq.setTickInterval(1)
        self.poffeq3Freq.setObjectName("poffeq3Freq")
        self.label_7 = QtWidgets.QLabel(self.ProcOffEQ3Frame)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.poffeq3FreqLcd = QtWidgets.QLCDNumber(self.ProcOffEQ3Frame)
        self.poffeq3FreqLcd.setGeometry(QtCore.QRect(250, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poffeq3FreqLcd.setFont(font)
        self.poffeq3FreqLcd.setAutoFillBackground(True)
        self.poffeq3FreqLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poffeq3FreqLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poffeq3FreqLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq3FreqLcd.setLineWidth(1)
        self.poffeq3FreqLcd.setDigitCount(4)
        self.poffeq3FreqLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq3FreqLcd.setObjectName("poffeq3FreqLcd")
        self.label_8 = QtWidgets.QLabel(self.ProcOffEQ3Frame)
        self.label_8.setGeometry(QtCore.QRect(40, 90, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.poffeq3Level = QtWidgets.QSlider(self.ProcOffEQ3Frame)
        self.poffeq3Level.setGeometry(QtCore.QRect(80, 90, 160, 22))
        self.poffeq3Level.setMinimum(-20)
        self.poffeq3Level.setMaximum(10)
        self.poffeq3Level.setSingleStep(1)
        self.poffeq3Level.setPageStep(1)
        self.poffeq3Level.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq3Level.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poffeq3Level.setTickInterval(1)
        self.poffeq3Level.setObjectName("poffeq3Level")
        self.poffeq3LevelLcd = QtWidgets.QLCDNumber(self.ProcOffEQ3Frame)
        self.poffeq3LevelLcd.setGeometry(QtCore.QRect(250, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poffeq3LevelLcd.setFont(font)
        self.poffeq3LevelLcd.setAutoFillBackground(True)
        self.poffeq3LevelLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poffeq3LevelLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poffeq3LevelLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq3LevelLcd.setLineWidth(1)
        self.poffeq3LevelLcd.setDigitCount(4)
        self.poffeq3LevelLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq3LevelLcd.setObjectName("poffeq3LevelLcd")
        self.label_9 = QtWidgets.QLabel(self.ProcOffEQ3Frame)
        self.label_9.setGeometry(QtCore.QRect(10, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.poffeq3Bw = QtWidgets.QSlider(self.ProcOffEQ3Frame)
        self.poffeq3Bw.setGeometry(QtCore.QRect(80, 130, 160, 22))
        self.poffeq3Bw.setMinimum(1)
        self.poffeq3Bw.setMaximum(10)
        self.poffeq3Bw.setSingleStep(1)
        self.poffeq3Bw.setPageStep(1)
        self.poffeq3Bw.setOrientation(QtCore.Qt.Horizontal)
        self.poffeq3Bw.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poffeq3Bw.setTickInterval(1)
        self.poffeq3Bw.setObjectName("poffeq3Bw")
        self.poffeq3BwLcd = QtWidgets.QLCDNumber(self.ProcOffEQ3Frame)
        self.poffeq3BwLcd.setGeometry(QtCore.QRect(250, 130, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poffeq3BwLcd.setFont(font)
        self.poffeq3BwLcd.setAutoFillBackground(True)
        self.poffeq3BwLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poffeq3BwLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poffeq3BwLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poffeq3BwLcd.setLineWidth(1)
        self.poffeq3BwLcd.setDigitCount(4)
        self.poffeq3BwLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poffeq3BwLcd.setObjectName("poffeq3BwLcd")
        self.poffeq3Control = QtWidgets.QComboBox(self.ProcOffEQ3Frame)
        self.poffeq3Control.setGeometry(QtCore.QRect(180, 20, 104, 21))
        self.poffeq3Control.setObjectName("poffeq3Control")
        self.poffeq3Control.addItem("")
        self.poffeq3Control.addItem("")
        self.label_23 = QtWidgets.QLabel(self.ProcOffEQ3Frame)
        self.label_23.setGeometry(QtCore.QRect(140, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.ProcOnFrame = QtWidgets.QGroupBox(self.centralwidget)
        self.ProcOnFrame.setGeometry(QtCore.QRect(20, 220, 941, 211))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ProcOnFrame.setFont(font)
        self.ProcOnFrame.setAutoFillBackground(False)
        self.ProcOnFrame.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.ProcOnFrame.setFlat(False)
        self.ProcOnFrame.setObjectName("ProcOnFrame")
        self.ProcOnEQ1Frame = QtWidgets.QGroupBox(self.ProcOnFrame)
        self.ProcOnEQ1Frame.setGeometry(QtCore.QRect(10, 30, 301, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ProcOnEQ1Frame.setFont(font)
        self.ProcOnEQ1Frame.setAutoFillBackground(False)
        self.ProcOnEQ1Frame.setFlat(False)
        self.ProcOnEQ1Frame.setObjectName("ProcOnEQ1Frame")
        self.poneq1Freq = QtWidgets.QSlider(self.ProcOnEQ1Frame)
        self.poneq1Freq.setGeometry(QtCore.QRect(80, 50, 160, 22))
        self.poneq1Freq.setMinimum(1)
        self.poneq1Freq.setMaximum(7)
        self.poneq1Freq.setSingleStep(1)
        self.poneq1Freq.setPageStep(1)
        self.poneq1Freq.setOrientation(QtCore.Qt.Horizontal)
        self.poneq1Freq.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poneq1Freq.setTickInterval(1)
        self.poneq1Freq.setObjectName("poneq1Freq")
        self.label_10 = QtWidgets.QLabel(self.ProcOnEQ1Frame)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.poneq1FreqLcd = QtWidgets.QLCDNumber(self.ProcOnEQ1Frame)
        self.poneq1FreqLcd.setGeometry(QtCore.QRect(250, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poneq1FreqLcd.setFont(font)
        self.poneq1FreqLcd.setAutoFillBackground(True)
        self.poneq1FreqLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poneq1FreqLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poneq1FreqLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq1FreqLcd.setLineWidth(1)
        self.poneq1FreqLcd.setDigitCount(4)
        self.poneq1FreqLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq1FreqLcd.setObjectName("poneq1FreqLcd")
        self.label_11 = QtWidgets.QLabel(self.ProcOnEQ1Frame)
        self.label_11.setGeometry(QtCore.QRect(40, 90, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.poneq1Level = QtWidgets.QSlider(self.ProcOnEQ1Frame)
        self.poneq1Level.setGeometry(QtCore.QRect(80, 90, 160, 22))
        self.poneq1Level.setMinimum(-20)
        self.poneq1Level.setMaximum(10)
        self.poneq1Level.setSingleStep(1)
        self.poneq1Level.setPageStep(1)
        self.poneq1Level.setOrientation(QtCore.Qt.Horizontal)
        self.poneq1Level.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poneq1Level.setTickInterval(1)
        self.poneq1Level.setObjectName("poneq1Level")
        self.poneq1LevelLcd = QtWidgets.QLCDNumber(self.ProcOnEQ1Frame)
        self.poneq1LevelLcd.setGeometry(QtCore.QRect(250, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poneq1LevelLcd.setFont(font)
        self.poneq1LevelLcd.setAutoFillBackground(True)
        self.poneq1LevelLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poneq1LevelLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poneq1LevelLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq1LevelLcd.setLineWidth(1)
        self.poneq1LevelLcd.setDigitCount(4)
        self.poneq1LevelLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq1LevelLcd.setObjectName("poneq1LevelLcd")
        self.label_12 = QtWidgets.QLabel(self.ProcOnEQ1Frame)
        self.label_12.setGeometry(QtCore.QRect(10, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.poneq1Bw = QtWidgets.QSlider(self.ProcOnEQ1Frame)
        self.poneq1Bw.setGeometry(QtCore.QRect(80, 130, 160, 22))
        self.poneq1Bw.setMinimum(1)
        self.poneq1Bw.setMaximum(10)
        self.poneq1Bw.setSingleStep(1)
        self.poneq1Bw.setPageStep(1)
        self.poneq1Bw.setOrientation(QtCore.Qt.Horizontal)
        self.poneq1Bw.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poneq1Bw.setTickInterval(1)
        self.poneq1Bw.setObjectName("poneq1Bw")
        self.poneq1BwLcd = QtWidgets.QLCDNumber(self.ProcOnEQ1Frame)
        self.poneq1BwLcd.setGeometry(QtCore.QRect(250, 130, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poneq1BwLcd.setFont(font)
        self.poneq1BwLcd.setAutoFillBackground(True)
        self.poneq1BwLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poneq1BwLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poneq1BwLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq1BwLcd.setLineWidth(1)
        self.poneq1BwLcd.setDigitCount(4)
        self.poneq1BwLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq1BwLcd.setObjectName("poneq1BwLcd")
        self.label_24 = QtWidgets.QLabel(self.ProcOnEQ1Frame)
        self.label_24.setGeometry(QtCore.QRect(140, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.poneq1Control = QtWidgets.QComboBox(self.ProcOnEQ1Frame)
        self.poneq1Control.setGeometry(QtCore.QRect(180, 20, 104, 21))
        self.poneq1Control.setObjectName("poneq1Control")
        self.poneq1Control.addItem("")
        self.poneq1Control.addItem("")
        self.ProcOnEQ2Frame = QtWidgets.QGroupBox(self.ProcOnFrame)
        self.ProcOnEQ2Frame.setGeometry(QtCore.QRect(320, 30, 301, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ProcOnEQ2Frame.setFont(font)
        self.ProcOnEQ2Frame.setAutoFillBackground(False)
        self.ProcOnEQ2Frame.setFlat(False)
        self.ProcOnEQ2Frame.setObjectName("ProcOnEQ2Frame")
        self.poneq2Freq = QtWidgets.QSlider(self.ProcOnEQ2Frame)
        self.poneq2Freq.setGeometry(QtCore.QRect(80, 50, 160, 22))
        self.poneq2Freq.setMinimum(7)
        self.poneq2Freq.setMaximum(15)
        self.poneq2Freq.setSingleStep(1)
        self.poneq2Freq.setPageStep(1)
        self.poneq2Freq.setProperty("value", 7)
        self.poneq2Freq.setOrientation(QtCore.Qt.Horizontal)
        self.poneq2Freq.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poneq2Freq.setTickInterval(1)
        self.poneq2Freq.setObjectName("poneq2Freq")
        self.label_13 = QtWidgets.QLabel(self.ProcOnEQ2Frame)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.poneq2FreqLcd = QtWidgets.QLCDNumber(self.ProcOnEQ2Frame)
        self.poneq2FreqLcd.setGeometry(QtCore.QRect(250, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poneq2FreqLcd.setFont(font)
        self.poneq2FreqLcd.setAutoFillBackground(True)
        self.poneq2FreqLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poneq2FreqLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poneq2FreqLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq2FreqLcd.setLineWidth(1)
        self.poneq2FreqLcd.setDigitCount(4)
        self.poneq2FreqLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq2FreqLcd.setObjectName("poneq2FreqLcd")
        self.label_14 = QtWidgets.QLabel(self.ProcOnEQ2Frame)
        self.label_14.setGeometry(QtCore.QRect(40, 90, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.poneq2Level = QtWidgets.QSlider(self.ProcOnEQ2Frame)
        self.poneq2Level.setGeometry(QtCore.QRect(80, 90, 160, 22))
        self.poneq2Level.setMinimum(-20)
        self.poneq2Level.setMaximum(10)
        self.poneq2Level.setSingleStep(1)
        self.poneq2Level.setPageStep(1)
        self.poneq2Level.setOrientation(QtCore.Qt.Horizontal)
        self.poneq2Level.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poneq2Level.setTickInterval(1)
        self.poneq2Level.setObjectName("poneq2Level")
        self.poneq2LevelLcd = QtWidgets.QLCDNumber(self.ProcOnEQ2Frame)
        self.poneq2LevelLcd.setGeometry(QtCore.QRect(250, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poneq2LevelLcd.setFont(font)
        self.poneq2LevelLcd.setAutoFillBackground(True)
        self.poneq2LevelLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poneq2LevelLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poneq2LevelLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq2LevelLcd.setLineWidth(1)
        self.poneq2LevelLcd.setDigitCount(4)
        self.poneq2LevelLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq2LevelLcd.setObjectName("poneq2LevelLcd")
        self.label_15 = QtWidgets.QLabel(self.ProcOnEQ2Frame)
        self.label_15.setGeometry(QtCore.QRect(10, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.poneq2Bw = QtWidgets.QSlider(self.ProcOnEQ2Frame)
        self.poneq2Bw.setGeometry(QtCore.QRect(80, 130, 160, 22))
        self.poneq2Bw.setMinimum(1)
        self.poneq2Bw.setMaximum(10)
        self.poneq2Bw.setSingleStep(1)
        self.poneq2Bw.setPageStep(1)
        self.poneq2Bw.setOrientation(QtCore.Qt.Horizontal)
        self.poneq2Bw.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poneq2Bw.setTickInterval(1)
        self.poneq2Bw.setObjectName("poneq2Bw")
        self.poneq2BwLcd = QtWidgets.QLCDNumber(self.ProcOnEQ2Frame)
        self.poneq2BwLcd.setGeometry(QtCore.QRect(250, 130, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poneq2BwLcd.setFont(font)
        self.poneq2BwLcd.setAutoFillBackground(True)
        self.poneq2BwLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poneq2BwLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poneq2BwLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq2BwLcd.setLineWidth(1)
        self.poneq2BwLcd.setDigitCount(4)
        self.poneq2BwLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq2BwLcd.setObjectName("poneq2BwLcd")
        self.poneq2Control = QtWidgets.QComboBox(self.ProcOnEQ2Frame)
        self.poneq2Control.setGeometry(QtCore.QRect(180, 20, 104, 21))
        self.poneq2Control.setObjectName("poneq2Control")
        self.poneq2Control.addItem("")
        self.poneq2Control.addItem("")
        self.label_25 = QtWidgets.QLabel(self.ProcOnEQ2Frame)
        self.label_25.setGeometry(QtCore.QRect(140, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.ProcOnEQ3Frame = QtWidgets.QGroupBox(self.ProcOnFrame)
        self.ProcOnEQ3Frame.setGeometry(QtCore.QRect(630, 30, 301, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ProcOnEQ3Frame.setFont(font)
        self.ProcOnEQ3Frame.setAutoFillBackground(False)
        self.ProcOnEQ3Frame.setFlat(False)
        self.ProcOnEQ3Frame.setObjectName("ProcOnEQ3Frame")
        self.poneq3Freq = QtWidgets.QSlider(self.ProcOnEQ3Frame)
        self.poneq3Freq.setGeometry(QtCore.QRect(80, 50, 160, 22))
        self.poneq3Freq.setMinimum(15)
        self.poneq3Freq.setMaximum(32)
        self.poneq3Freq.setSingleStep(1)
        self.poneq3Freq.setPageStep(1)
        self.poneq3Freq.setOrientation(QtCore.Qt.Horizontal)
        self.poneq3Freq.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poneq3Freq.setTickInterval(1)
        self.poneq3Freq.setObjectName("poneq3Freq")
        self.label_16 = QtWidgets.QLabel(self.ProcOnEQ3Frame)
        self.label_16.setGeometry(QtCore.QRect(10, 50, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.poneq3FreqLcd = QtWidgets.QLCDNumber(self.ProcOnEQ3Frame)
        self.poneq3FreqLcd.setGeometry(QtCore.QRect(250, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poneq3FreqLcd.setFont(font)
        self.poneq3FreqLcd.setAutoFillBackground(True)
        self.poneq3FreqLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poneq3FreqLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poneq3FreqLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq3FreqLcd.setLineWidth(1)
        self.poneq3FreqLcd.setDigitCount(4)
        self.poneq3FreqLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq3FreqLcd.setObjectName("poneq3FreqLcd")
        self.label_17 = QtWidgets.QLabel(self.ProcOnEQ3Frame)
        self.label_17.setGeometry(QtCore.QRect(40, 90, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.poneq3Level = QtWidgets.QSlider(self.ProcOnEQ3Frame)
        self.poneq3Level.setGeometry(QtCore.QRect(80, 90, 160, 22))
        self.poneq3Level.setMinimum(-20)
        self.poneq3Level.setMaximum(10)
        self.poneq3Level.setSingleStep(1)
        self.poneq3Level.setPageStep(1)
        self.poneq3Level.setOrientation(QtCore.Qt.Horizontal)
        self.poneq3Level.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poneq3Level.setTickInterval(1)
        self.poneq3Level.setObjectName("poneq3Level")
        self.poneq3LevelLcd = QtWidgets.QLCDNumber(self.ProcOnEQ3Frame)
        self.poneq3LevelLcd.setGeometry(QtCore.QRect(250, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poneq3LevelLcd.setFont(font)
        self.poneq3LevelLcd.setAutoFillBackground(True)
        self.poneq3LevelLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poneq3LevelLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poneq3LevelLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq3LevelLcd.setLineWidth(1)
        self.poneq3LevelLcd.setDigitCount(4)
        self.poneq3LevelLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq3LevelLcd.setObjectName("poneq3LevelLcd")
        self.label_18 = QtWidgets.QLabel(self.ProcOnEQ3Frame)
        self.label_18.setGeometry(QtCore.QRect(10, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.poneq3Bw = QtWidgets.QSlider(self.ProcOnEQ3Frame)
        self.poneq3Bw.setGeometry(QtCore.QRect(80, 130, 160, 22))
        self.poneq3Bw.setMinimum(1)
        self.poneq3Bw.setMaximum(10)
        self.poneq3Bw.setSingleStep(1)
        self.poneq3Bw.setPageStep(1)
        self.poneq3Bw.setOrientation(QtCore.Qt.Horizontal)
        self.poneq3Bw.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.poneq3Bw.setTickInterval(1)
        self.poneq3Bw.setObjectName("poneq3Bw")
        self.poneq3BwLcd = QtWidgets.QLCDNumber(self.ProcOnEQ3Frame)
        self.poneq3BwLcd.setGeometry(QtCore.QRect(250, 130, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.poneq3BwLcd.setFont(font)
        self.poneq3BwLcd.setAutoFillBackground(True)
        self.poneq3BwLcd.setStyleSheet("QLCDNumber{color:rgb(0, 0, 0)}\n"
"")
        self.poneq3BwLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.poneq3BwLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poneq3BwLcd.setLineWidth(1)
        self.poneq3BwLcd.setDigitCount(4)
        self.poneq3BwLcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.poneq3BwLcd.setObjectName("poneq3BwLcd")
        self.label_26 = QtWidgets.QLabel(self.ProcOnEQ3Frame)
        self.label_26.setGeometry(QtCore.QRect(140, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.poneq3Control = QtWidgets.QComboBox(self.ProcOnEQ3Frame)
        self.poneq3Control.setGeometry(QtCore.QRect(180, 20, 104, 21))
        self.poneq3Control.setObjectName("poneq3Control")
        self.poneq3Control.addItem("")
        self.poneq3Control.addItem("")
        self.radioConnectFrame = QtWidgets.QGroupBox(self.centralwidget)
        self.radioConnectFrame.setGeometry(QtCore.QRect(280, 430, 361, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioConnectFrame.setFont(font)
        self.radioConnectFrame.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.radioConnectFrame.setObjectName("radioConnectFrame")
        self.comPortInput = QtWidgets.QComboBox(self.radioConnectFrame)
        self.comPortInput.setGeometry(QtCore.QRect(10, 60, 221, 26))
        self.comPortInput.setObjectName("comPortInput")
        self.comPortInput.addItem("")
        self.baudRate = QtWidgets.QComboBox(self.radioConnectFrame)
        self.baudRate.setGeometry(QtCore.QRect(240, 60, 104, 26))
        self.baudRate.setObjectName("baudRate")
        self.baudRate.addItem("")
        self.baudRate.addItem("")
        self.baudRate.addItem("")
        self.baudRate.addItem("")
        self.baudRate.addItem("")
        self.radioConnect = QtWidgets.QPushButton(self.radioConnectFrame)
        self.radioConnect.setGeometry(QtCore.QRect(10, 90, 101, 32))
        self.radioConnect.setObjectName("radioConnect")
        self.label_19 = QtWidgets.QLabel(self.radioConnectFrame)
        self.label_19.setGeometry(QtCore.QRect(20, 40, 60, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.radioConnectFrame)
        self.label_20.setGeometry(QtCore.QRect(260, 40, 71, 16))
        self.label_20.setObjectName("label_20")
        self.radioDisconnect = QtWidgets.QPushButton(self.radioConnectFrame)
        self.radioDisconnect.setGeometry(QtCore.QRect(130, 90, 91, 32))
        self.radioDisconnect.setObjectName("radioDisconnect")
        self.VoxProcFrame = QtWidgets.QGroupBox(self.centralwidget)
        self.VoxProcFrame.setGeometry(QtCore.QRect(20, 430, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.VoxProcFrame.setFont(font)
        self.VoxProcFrame.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.VoxProcFrame.setObjectName("VoxProcFrame")
        self.voiceprocControl = QtWidgets.QComboBox(self.VoxProcFrame)
        self.voiceprocControl.setGeometry(QtCore.QRect(10, 30, 104, 26))
        self.voiceprocControl.setObjectName("voiceprocControl")
        self.voiceprocControl.addItem("")
        self.voiceprocControl.addItem("")
        self.MicEqFrame = QtWidgets.QGroupBox(self.centralwidget)
        self.MicEqFrame.setGeometry(QtCore.QRect(150, 430, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.MicEqFrame.setFont(font)
        self.MicEqFrame.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.MicEqFrame.setObjectName("MicEqFrame")
        self.micEqControl = QtWidgets.QComboBox(self.MicEqFrame)
        self.micEqControl.setGeometry(QtCore.QRect(10, 30, 104, 26))
        self.micEqControl.setObjectName("micEqControl")
        self.micEqControl.addItem("")
        self.micEqControl.addItem("")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(770, 480, 60, 16))
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.statusGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.statusGroupBox.setGeometry(QtCore.QRect(649, 429, 311, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.statusGroupBox.setFont(font)
        self.statusGroupBox.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.statusGroupBox.setObjectName("statusGroupBox")
        self.messageLabel = QtWidgets.QLabel(self.statusGroupBox)
        self.messageLabel.setGeometry(QtCore.QRect(9, 35, 291, 91))
        self.messageLabel.setText("")
        self.messageLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.messageLabel.setWordWrap(True)
        self.messageLabel.setObjectName("messageLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 977, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comPortInput.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ProcOffFrame.setTitle(_translate("MainWindow", "Voice Processor Off EQ Settings"))
        self.ProcOffEQ1Frame.setTitle(_translate("MainWindow", "EQ 1"))
        self.label.setText(_translate("MainWindow", "Frequency"))
        self.label_2.setText(_translate("MainWindow", "Level"))
        self.label_3.setText(_translate("MainWindow", "Bandwidth"))
        self.poffeq1Control.setToolTip(_translate("MainWindow", "Turns the parametric EQ on or off"))
        self.poffeq1Control.setItemText(0, _translate("MainWindow", "OFF"))
        self.poffeq1Control.setItemText(1, _translate("MainWindow", "ON"))
        self.label_21.setText(_translate("MainWindow", "On/Off"))
        self.ProcOffEQ2Frame.setTitle(_translate("MainWindow", "EQ 2"))
        self.label_4.setText(_translate("MainWindow", "Frequency"))
        self.label_5.setText(_translate("MainWindow", "Level"))
        self.label_6.setText(_translate("MainWindow", "Bandwidth"))
        self.poffeq2Control.setToolTip(_translate("MainWindow", "Turns the parametric EQ on or off"))
        self.poffeq2Control.setItemText(0, _translate("MainWindow", "OFF"))
        self.poffeq2Control.setItemText(1, _translate("MainWindow", "ON"))
        self.label_22.setText(_translate("MainWindow", "On/Off"))
        self.ProcOffEQ3Frame.setTitle(_translate("MainWindow", "EQ 3"))
        self.label_7.setText(_translate("MainWindow", "Frequency"))
        self.label_8.setText(_translate("MainWindow", "Level"))
        self.label_9.setText(_translate("MainWindow", "Bandwidth"))
        self.poffeq3Control.setToolTip(_translate("MainWindow", "Turns the parametric EQ on or off"))
        self.poffeq3Control.setItemText(0, _translate("MainWindow", "OFF"))
        self.poffeq3Control.setItemText(1, _translate("MainWindow", "ON"))
        self.label_23.setText(_translate("MainWindow", "On/Off"))
        self.ProcOnFrame.setTitle(_translate("MainWindow", "Voice Processor On EQ Settings"))
        self.ProcOnEQ1Frame.setTitle(_translate("MainWindow", "EQ 1"))
        self.label_10.setText(_translate("MainWindow", "Frequency"))
        self.label_11.setText(_translate("MainWindow", "Level"))
        self.label_12.setText(_translate("MainWindow", "Bandwidth"))
        self.label_24.setText(_translate("MainWindow", "On/Off"))
        self.poneq1Control.setToolTip(_translate("MainWindow", "Turns the parametric EQ on or off"))
        self.poneq1Control.setItemText(0, _translate("MainWindow", "OFF"))
        self.poneq1Control.setItemText(1, _translate("MainWindow", "ON"))
        self.ProcOnEQ2Frame.setTitle(_translate("MainWindow", "EQ 2"))
        self.label_13.setText(_translate("MainWindow", "Frequency"))
        self.label_14.setText(_translate("MainWindow", "Level"))
        self.label_15.setText(_translate("MainWindow", "Bandwidth"))
        self.poneq2Control.setToolTip(_translate("MainWindow", "Turns the parametric EQ on or off"))
        self.poneq2Control.setItemText(0, _translate("MainWindow", "OFF"))
        self.poneq2Control.setItemText(1, _translate("MainWindow", "ON"))
        self.label_25.setText(_translate("MainWindow", "On/Off"))
        self.ProcOnEQ3Frame.setTitle(_translate("MainWindow", "EQ 3"))
        self.label_16.setText(_translate("MainWindow", "Frequency"))
        self.label_17.setText(_translate("MainWindow", "Level"))
        self.label_18.setText(_translate("MainWindow", "Bandwidth"))
        self.label_26.setText(_translate("MainWindow", "On/Off"))
        self.poneq3Control.setToolTip(_translate("MainWindow", "Turns the parametric EQ on or off"))
        self.poneq3Control.setItemText(0, _translate("MainWindow", "OFF"))
        self.poneq3Control.setItemText(1, _translate("MainWindow", "ON"))
        self.radioConnectFrame.setTitle(_translate("MainWindow", "Radio Connection"))
        self.comPortInput.setItemText(0, _translate("MainWindow", "Select Port"))
        self.baudRate.setItemText(0, _translate("MainWindow", "Set Baud"))
        self.baudRate.setItemText(1, _translate("MainWindow", "4800"))
        self.baudRate.setItemText(2, _translate("MainWindow", "9600"))
        self.baudRate.setItemText(3, _translate("MainWindow", "19200"))
        self.baudRate.setItemText(4, _translate("MainWindow", "38400"))
        self.radioConnect.setText(_translate("MainWindow", "Connect"))
        self.label_19.setText(_translate("MainWindow", "Com Port"))
        self.label_20.setText(_translate("MainWindow", "Baud Rate"))
        self.radioDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.VoxProcFrame.setTitle(_translate("MainWindow", "Voice Processor"))
        self.voiceprocControl.setItemText(0, _translate("MainWindow", "Off"))
        self.voiceprocControl.setItemText(1, _translate("MainWindow", "On"))
        self.MicEqFrame.setTitle(_translate("MainWindow", "Mic EQ"))
        self.micEqControl.setItemText(0, _translate("MainWindow", "Off"))
        self.micEqControl.setItemText(1, _translate("MainWindow", "On"))
        self.statusGroupBox.setTitle(_translate("MainWindow", "Status Messages"))

